hermes:
  build: .
  links: 
   - mitie
   - cliff
   - topics
   - joshua
#   - stanford
  ports:
   - "5000:5000"
mitie:
  build: mitie/.
cliff:
  build: cliff/.
topics:
  build: topics/.
joshua:
  image: caerusassociates/joshua:6.0.1
  command: python /opt/joshua-v6.0.1/app.py
#stanford:
#  build: stanford/.
