hermes:
  build: .
  links: 
   - mitie
   - cliff
   - topics
   - stanford
  ports:
   - "5000:5000"
mitie:
  build: mitie/.
cliff:
  build: cliff/.
topics:
  build: topics/.
stanford:
  build: stanford/.
